# mkdocs.yml
site_name: Древние свитки Твирела и Зоэрна
nav:
  - Домашняя: index.md
  - Хронология: hronology.md
  - Истории и книги:
      - Сны демонов (книга): stories/Сны демонов.md
  - Миры:
      - Твирел: worlds/Твирел.md
  - Исторические события:
      - Легенда о Граннусе-Освободителе: history/Легенда о Граннусе-Освободителе.md
  - Персонажи:
      - Брайан: characters/Брайан.md
      - Граннус-Освободитель: characters/Граннус-Освободитель.md
  - Населенные пункты:
      - Деревня Эмбруд: settlements/Деверня Эмбруд.md

plugins:
  - search
  - roamlinks
  - obsidian-support

theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
  language: ru