# mkdocs.yml
site_name: Древние свитки Твирела и Зоэрна
nav:
  - Домашняя: index.md
  - Персонажи:
      - Брайан: characters/Braian.md
  - Населенные пункты:
      - Деревня Эмбруд: settlements/Деверня Эмбруд.md
  - Мифы и легенды:
      - Легенда о Граннусе: legends/Легенда о Граннусе.md

plugins:
  - search
  - roamlinks 

theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
    scheme: slate