# mkdocs.yml
site_name: Древние свитки Твирела и Зоэрна
nav:
  - Домашняя: index.md
  - Глобальные явления: Глобальные явления.md
  - Твирел: Твирел.md
  - Зоэрн: Зоэрн.md

plugins:
  - search
  - roamlinks
  - obsidian-support

theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
  language: ru