# mkdocs.yml
site_name: Древние свитки Твирела и Зоэрна
nav:
  - Домашняя: index.md
  - Персонажи:
      - Брайан: characters/Braian.md
  - Населенные пункты:
      - Деревня Эмбруд: settlements/Деревня Эмбруд.md
  - Мифы и легенды:
      - Легенда о Граннусе: legends/Легенда о Граннусе.md
theme:
  name: material