# mkdocs.yml
site_name: Древние свитки Твирела и Зоэрна
nav:
  - Домашняя: index.md
  - Хронология: hronology.md
  - Истории и книги:
      - Сны демонов (книга): stories/Сны демонов.md
  - Миры:
      - Твирел: worlds/Твирел.md
  - Исторические события:
      - Восхождение Тарлока Осквернителя: history/Восхождение Тарлока Осквернителя.md
      - Гражданская война 2149 – 2153 г.г. ПЭ: history/Гражданская война 2149 – 2153 г.г. ПЭ.md
  - Государства:
      - Королевство Арверн: states/Королевство Арверн.md
      - Королевство Кимбает: states/Королевство Кимбает.md
      - Королевство Галат: states/Королевство Галат.md
      - Империя людей: states/Империя людей.md
      - Союз вольных городов: states/Союз вольных городов.md
  - Персонажи:
      - Тарлок I "Осквернитель": characters/Император Тарлок I "Осквернитель".md
      - Граннус-Освободитель: characters/Граннус-Освободитель.md
      - Брайан: characters/Брайан.md
  - Населенные пункты:
      - Деревня Эмбруд: settlements/Деверня Эмбруд.md
      - Замок тлеющей славы: settlements/Замок тлеющей славы.md
  - Явления:
      - Магия: phenomenon/Магия.md

plugins:
  - search
  - roamlinks
  - obsidian-support

theme:
  name: material
  palette:
    primary: blue grey
    accent: teal
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
  language: ru