[project]
name = "the-elder-scrolls-of-tvirel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.14",
    "mkdocs-obsidian-support-plugin>=1.4.1",
    "mkdocs-roamlinks-plugin>=0.3.2",
]
